CSLab5/Controllers/AchievementController.cs
using CSDBapp;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model;

namespace CSLab5.Controllers
{
    public class AchievementController : Controller
    {
        public async Task<IActionResult> Index()
        {
            using (GameDb db = new GameDb())
            {
                return View(await db.Achievements.Include(k => k.PlayerAchievement).ToListAsync());
            }
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Achievement achievement)
        {
            if (ModelState.IsValid)
            {
                await CRUD<Achievement>.GetInstance().AddAsync(achievement);;
                
                FileLoggerTS.GetInstance().LogMessage($"Create achievement {achievement.Name}");
                return RedirectToAction("Index");
            }
            return View(achievement);
        }
        public async Task<IActionResult> Edit(int id)
        {

            Achievement? ach = await CRUD<Achievement>.GetInstance().GetByIdAsync(id);
            if (ach != null)
            {
                return View(ach);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Achievement achievement)
        {
            if (ModelState.IsValid)
            {
                await CRUD<Achievement>.GetInstance().UpdateAsync(achievement, achievement.Id);

                FileLoggerTS.GetInstance().LogMessage($"Edit achievement {achievement.Name}");
                return RedirectToAction("Index");
            }
            return View(achievement);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            CRUD<Achievement> crud = CRUD<Achievement>.GetInstance();
            FileLoggerTS.GetInstance().LogMessage($"Delete achievement {(await crud.GetByIdAsync(id))?.Name}");
            await crud.DeleteAsync(id);
            return RedirectToAction("Index");
        }

    }
}

CSLab5/Views/Achievement/Create.cshtml
@model Model.Achievement
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}

<!doctype html>
<html>
<head>
    <title>Test</title>
    <meta charset="utf-8" />
</head>
<body>
    <h2>Добавление достижения</h2>

    <form asp-action="Create" asp-controller="Achievement">
        <p>
            <label asp-for="Name">Имя</label><br />
            <input type="text" asp-for="Name" />
        </p>
        <p>
            <label asp-for="Description">Описание</label><br />
            <input type="text" asp-for="Description"/>
        </p>
        <p>
            <label asp-for="Reward">Награда</label><br />
            <input type="number" asp-for="Reward" step="0.01" />
        </p>
        <p>
            <input type="submit" value="Добавить"/>
        </p>

    </form>
    <p><a asp-action="Index">Назад</a></p>
</body>
</html>

CSLab5/Views/Achievement/Edit.cshtml
@model Model.Achievement
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}

<!doctype html>
<html>
<head>
    <title>Test</title>
    <meta charset="utf-8" />
</head>
<body>
    <h2>Редактирование достижения</h2>

    <form asp-action="Edit" asp-controller="Achievement">
        <input type="hidden" asp-for="Id" />
        <p>
            <label asp-for="Name">Имя</label><br />
            <input type="text" asp-for="Name" />
        </p>
        <p>
            <label asp-for="Description">Описание</label><br />
            <input type="text" asp-for="Description" />
        </p>
        <p>
            <label asp-for="Reward">Награда</label><br />
            <input type="number" asp-for="Reward" step="0.01" />
        </p>
        <p>
            <input type="submit" value="Сохранить" />
        </p>

    </form>
    <p><a asp-action="Index">Назад</a></p>
</body>
</html>

CSLab5/Views/Achievement/Index.cshtml
@model IEnumerable<Model.Achievement>

<!doctype html>
<html>
<head>
    <title>Test</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/Content/StyleSheet.css" />
</head>
<body>
    <h2>Список достижений</h2>
    <p><a asp-action="Create">Добавить достижение</a></p>
    <table class="table">
        <tr><th>Имя</th><th>Описание</th><th>Награда</th><th>Игроки с достижением</th></tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td class ="description">@item.Description</td>
                <td>@item.Reward</td>
                <td>
                    @if (item.PlayerAchievement.Count >= 1)
                    {
                        <details>
                            <summary>Список</summary>
                            <ul>
                                @foreach (var player in item.PlayerAchievement)
                                {
                                    <li>@player.Username</li>
                                }
                            </ul>
                        </details>
                    }
                    else
                    {
                        @("-")
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="Achievement" asp-route-id="@item.Id">Изменить</a>
                </td>
                <td>
                    <form asp-controller="Achievement" asp-action="Delete" method="post" asp-route-id="@item.Id">
                        <input type="submit" value="Удалить" />
                    </form>
                </td>
            </tr>
        }
    </table>
    <p><a asp-controller="Home" asp-action="Index">Назад</a></p>
</body>
</html>