CSLab5/Controllers/KingdomController.cs
using CSDBapp;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model;
using System.Security.Permissions;

namespace CSLab5.Controllers
{
    public class KingdomController : Controller
    {
        public async Task<IActionResult> Index()
        {
            using (GameDb db = new GameDb()) {
                return View(await db.Kingdoms.Include(k => k.Players).ToListAsync());
            }
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Kingdom kingdom)
        {
            if (ModelState.IsValid)
            {
                await CRUD<Kingdom>.GetInstance().AddAsync(kingdom); ;

                FileLoggerTS.GetInstance().LogMessage($"Create kingdom {kingdom.Name}");
                return RedirectToAction("Index");
            }
            return View(kingdom);
        }
        public async Task<IActionResult> Edit(int id)
        {

            Kingdom? king = await CRUD<Kingdom>.GetInstance().GetByIdAsync(id);
            if (king != null)
            {
                return View(king);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Kingdom kingdom)
        {
            if (ModelState.IsValid)
            {
                await CRUD<Kingdom>.GetInstance().UpdateAsync(kingdom, kingdom.Id);

                FileLoggerTS.GetInstance().LogMessage($"Edit kingdom {kingdom.Name}");
                return RedirectToAction("Index");
            }
            return View(kingdom);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            CRUD<Kingdom> crud = CRUD<Kingdom>.GetInstance();
            FileLoggerTS.GetInstance().LogMessage($"Delete kingdom {(await crud.GetByIdAsync(id))?.Name}");
            await crud.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

CSLab5/Views/Kingdom/Create.cshtml
@model Model.Kingdom
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}

<!doctype html>
<html>
<head>
    <title>Test</title>
    <meta charset="utf-8" />
</head>
<body>
    <h2>Добавление королевства</h2>

    <form asp-action="Create" asp-controller="Kingdom">
        <p>
            <label asp-for="Name">Имя</label><br />
            <input type="text" asp-for="Name" />
        </p>
        <p>
            <label asp-for="Level">Уровень</label><br />
            <input type="number" asp-for="Level"/>
        </p>
        <p>
            <input type="submit" value="Добавить"/>
        </p>

    </form>
    <p><a asp-action="Index">Назад</a></p>
</body>
</html>

CSLab5/Views/Kingdom/Edit.cshtml
@model Model.Kingdom
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}

<!doctype html>
<html>
<head>
    <title>Test</title>
    <meta charset="utf-8" />
</head>
<body>
    <h2>Редактирование королевства</h2>

    <form asp-action="Edit" asp-controller="Kingdom">
        <input type="hidden" asp-for="Id" />
        <p>
            <label asp-for="Name">Имя</label><br />
            <input type="text" asp-for="Name" />
        </p>
        <p>
            <label asp-for="Level">Level</label><br />
            <input type="number" asp-for="Level"/>
        </p>
        <p>
            <input type="submit" value="Сохранить" />
        </p>

    </form>
    <p><a asp-action="Index">Назад</a></p>
</body>
</html>

CSLab5/Views/Kingdom/Index.cshtml
@model IEnumerable<Model.Kingdom>

<!doctype html>
<html>
<head>
    <title>Test</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/Content/StyleSheet.css" />
</head>
<body>
    <h2>Список Королевств</h2>
    <p><a asp-action="Create">Добавить королевство</a></p>
    <table class="table">
        <tr><th>Имя</th><th>Уровень</th><th>Игроки</th>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Level</td>
                <td>
                        @if (item.Players.Count >= 1){
                            <details>
                            <summary>Список</summary>
                            <ul>
                            @foreach (var player in item.Players)
                            {
                            <li>@player.Username</li>
                            }
                            </ul>
                            </details>
                            
                        }
                        else
                        {
                            @("-")
                        }
                    </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a>

                </td>
                <td>
                    <form asp-action="Delete" method="post" asp-route-id="@item.Id">
                        <input type="submit" value="Удалить" />
                    </form>
                </td>
            </tr>
        }
    </table>
    <p><a asp-controller="Home" asp-action="Index">Назад</a></p>
</body>
</html>